convert ./images/* json: > ./json/exif.json
echo Successfully extracted exif data from images...
node ./js/parseCoords.js > ./json/geoJson.json
node_modules/prettier/bin-prettier.js --write --loglevel silent './json/*.json' # --loglevel silent not respected with --> npm run format './json/*.json'
echo Successfully parsed exif data to geoJson...
